site_name: GCES KDE Linux Relatórios
theme:
  name: material
  language: pt-BR

nav:
  - Home: index.md
  - Geral:
    - Sprint 0: sprint0.md
  - Contribuições individuais:
    - Caio Lamego: contribuicoes_individuais/caiolamego/diarioDeBordo.md
    - Victório Lázaro: contribuicoes_individuais/victoriolazaro/diarioDeBordo.md
    - João Pedro: contribuicoes_individuais/joaopedro/diarioDeBordo.md
    - Diego Carlito: contribuicoes_individuais/diegocarlito/diarioDeBordo.md
    - João Capozzi: contribuicoes_individuais/joaocapozzi/diarioDeBordo.md
    - Felipe Amorim: contribuicoes_individuais/felipeamorim/diarioDeBordo.md
