site_name: GCES KDE Linux Relatórios
theme:
  name: material
  language: pt-BR

nav:
  - Home: index.md
  - Geral:
    - Sprint 0: sprint0.md
  - Contribuições individuais:
    - Caio Lamego: contribuicoes_individuais/caiolamego/diarioDeBordo.md